services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '50051:50051' # OTLP gRPC
      - '50052:50052' # OTLP HTTP
      - '50080:50080' # Prometheus metrics
    networks:
      - observability
    depends_on:
      - tempo

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '50081:9090'
    networks:
      - observability
    depends_on:
      - tempo

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-dashboard-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana-dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '4000:3000'
    networks:
      - observability
    depends_on:
      - prometheus
      - tempo

  # Tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root # Run as root to ensure write permissions
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo:rw
    ports:
      - '50061:3200' # Tempo HTTP query
      - '50062:9095' # Tempo gRPC query
      - '50063:4317' # OTLP gRPC
      - '50064:4318' # OTLP HTTP
      - '50065:9411' # Zipkin ingest
    networks:
      - observability

networks:
  observability:
    name: observability
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:
