apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-runner-sa
  namespace: test-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-runner-job-role
  namespace: test-runner
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-runner-job-rolebinding
  namespace: test-runner
subjects:
  - kind: ServiceAccount
    name: test-runner-sa
    namespace: test-runner
roleRef:
  kind: Role
  name: test-runner-job-role
  apiGroup: rbac.authorization.k8s.io

